language: python
os:
  - linux
python:
  - 3.7
services:
  - docker

jobs:
  include:
    - stage: Build Zigbee2mqtt Docker Images on AMD64
      script:
        - travis_wait 300 sleep infinity & $TRAVIS_BUILD_DIR/zigbee2mqtt/build.sh
    - stage: Build and Deploy Zigbee2mqtt images to Docker Hub
      if: type != pull_request AND (branch = master OR tag IS present)
      script:
        - travis_wait 300 sleep infinity & $TRAVIS_BUILD_DIR/zigbee2mqtt/distribute.sh

env:
  global:
    - ADDON_NAME="zigbee2mqtt"
    - AUTHOR="Viet Tien <ttvtien@gmail.com>"
    - GITHUB_URL="https://github.com/HomemateVN/ha/tree/master/zigbee2mqtt"