language: python
os:
  - linux
python:
  - 3.7
services:
  - docker
arch:
    - amd64
    - arm64

jobs:
  include:
    - stage: Build Zigbee2mqtt Docker Images for AMD64
      script:
        - $TRAVIS_BUILD_DIR/zigbee2mqtt/build.sh
    - stage: Build and Deploy Zigbee2mqtt images to Docker Hub
      if: type != pull_request AND (branch = master OR tag IS present)
      script:
        - $TRAVIS_BUILD_DIR/zigbee2mqtt/distribute.sh
    - arch: arm64
      stage: Build Zigbee2mqtt Docker Images for ARM64
      script:
        - $TRAVIS_BUILD_DIR/zigbee2mqtt/build.sh
    - arch: arm64
      stage: Build and Deploy Zigbee2mqtt images to Docker Hub
      if: type != pull_request AND (branch = master OR tag IS present)
      script:
        - $TRAVIS_BUILD_DIR/zigbee2mqtt/distribute.sh


env:
  global:
    - ADDON_NAME="zigbee2mqtt"
    - AUTHOR="Viet Tien <ttvtien@gmail.com>"
    - GITHUB_URL="https://github.com/HomemateVN/ha/tree/master/zigbee2mqtt"
